### ISSUE TITLE
イベント追加モーダルの外側をクリックすると、入力中でも警告なく閉じる

### ISSUE THREAD

**Issue by hibikine** [lapi-hotel-group/furport-front#150]
イベント追加モーダルの外側をクリックすると、入力中の内容が消えます。

## 環境
* Windows 10
* FireFox 78.0.2 (64 ビット)

## 再現手順
* https://www.furport.tk/events にアクセス
* 右下のプラスボタンを押してイベント追加モーダルを開く
* 適当な項目を入力する。ここでは例として、イベント名に「はつじゅー会5」と入力する
* モーダルの外側の黒いオーバーレイをクリックする
* モーダルが警告なく閉じ、入力途中の内容が消えてしまう

## 修正案
* モーダルを閉じる際に、何か入力内容が存在する場合には `window.confirm` を実行する。「入力途中の内容が消えてしまいますがよろしいですか？」などの文章で警告を出す。
* 警告を出しても引き続き閉じる場合はモーダルを閉じる。キャンセルした場合は閉じない。
* `NewEvent.js` の `Dialog` の引数に、 `onClickBackdrop` を追加すれば対応できそうです。

https://github.com/lapi-hotel-group/furport-front/blob/5e2b61e36351fc1a905513490135bea0b7b9bbdc/src/components/Events/NewEvent.js#L61

## 参考資料
* [Dialog API - Material UI](https://material-ui.com/api/dialog/#props)

**Comment by dragoneena12** [comment]
#208 で対応しました！ありがとうございます！
